Translate the section "How to Optimize" for pt-BR
dgryski/go-perfbook pull request #30
Opened 2018-10-11 02:30 UTC by vitordagamagodoy

Increase the translated parcel for pt-BR

2018-10-11 11:07 UTC, danielfireman requested changes
Great stuff! Only a few comments/suggestions below.

2018-10-11 11:07 UTC, danielfireman commented on performance-ptbr.md
> +Para o desenvolvimento de novos projetos, você não deve deixar o a avaliação de desempenho para o fim. É fácil dizer "depois eu faço", mas se o desempenho é realmente importante, isso deve ser consid
s/porblema/problemas

2018-10-11 11:07 UTC, danielfireman commented on performance-ptbr.md
> +Escreva código que você pode comparar. Perfilamento você pode fazer em sistemas maiores. Em _benchmarking_ você quer testar partes isoladas. Você precisa ser capaz de extrair e configurar o contexto
Suggestion:

From: Perfilamento você pode fazer em sistemas maiores. Em _benchmarking_ você quer testar partes isoladas.

To: Você pode fazer perfilamento em sistemas maiores, porém em _benchmarking_ você quer testar partes isoladas.

2018-10-11 11:07 UTC, danielfireman commented on performance-ptbr.md
> +Quando se está otimizando, você quer reduzir o trabalho que a CPU precisa fazer.
This sentence would replace the first sentence of the next paragraph, right?

2018-10-11 11:07 UTC, danielfireman commented on performance-ptbr.md
> +Um perfilador pode mostrar que muito tempo é gasto em uma rotina específica. Pode ser que esta seja uma rotina cara ou uma rotina barata
Remove unnecessary line break?

2018-10-11 12:24 UTC, vitordagamagodoy commented
@danielfireman thanks for your review. I fixed what you highlighted

2018-10-15 19:37 UTC, dgryski commented
Is this ready to merge?

2019-07-15 17:15 UTC, dialmformart approved these changes
That's a fine thing to merge! @dgryski

2019-07-15 17:16 UTC, merged