Update performance-ptbr.md
dgryski/go-perfbook pull request #53
Opened 2019-07-16 00:37 UTC by dialmformart

Translating the Concrete optimization tips section.

2019-07-19 20:09 UTC, danielfireman requested changes

2019-07-19 20:09 UTC, danielfireman commented on performance-ptbr.md
> +O trabalho de Jon Bentley em 1982, "Writing Efficient Programs", abordou a otimização de programas como um problema de engenharia: Benchmark. Analisar. Melhorar. Verificar. Iterar. Várias de suas dic
Repeated "é".

2019-07-19 20:09 UTC, danielfireman commented on performance-ptbr.md
> +Alterar seus dados significa adicionar ou alterar a representação dos dados que você está processando. Do ponto de vista de desempenho, alguns desses vai acabar mudando a complexidade O() que é assoc
s/vai/vão

2019-07-19 20:09 UTC, danielfireman commented on performance-ptbr.md
> +Idéias para aumentar sua estrutura de dados:
s/aumentar/melhorar

2019-07-19 20:09 UTC, danielfireman commented on performance-ptbr.md
> +  do nó raiz. Temos um pouco mais de trabalho para mantê-la atualizada, mas, em seguida, consultar
s/mas, em seguida,/porém

2019-07-19 20:09 UTC, danielfireman commented on performance-ptbr.md
> +  lista duplamente ligada para fazer a remoção do nó ter complexidade O (1). Algumas listas ignoradas mantêm uma "search
replace "listas ignoradas" for:
- Skip lists or
- "listas de saltos"

2019-07-19 20:09 UTC, danielfireman commented on performance-ptbr.md
> +* Índices de pesquisa extra
Índices extras de pesquisa

2019-07-19 20:09 UTC, danielfireman commented on performance-ptbr.md
> +  ID secundário (string). Em vez de iterar sobre a fatia, você pode aumentar
s/aumentar/incrementar

2019-07-19 20:09 UTC, danielfireman commented on performance-ptbr.md
> +  Por exemplo, manter um *bloom filter* de todos os elementos que você inseriu pode deixar que você retorne rapidamente "sem correspondência" para pesquisas. Estes precisam ser pequenos e rápidos par
s/Por exemplo, manter um *bloom filter* de todos os elementos que você inseriu pode deixar que você retorne rapidamente "sem correspondência" para pesquisas./Por exemplo, manter um *bloom filter* de todos os elementos inseridos pode fazer com que você retorne rapidamente consultas sem resultado.

2019-07-19 20:09 UTC, danielfireman commented on performance-ptbr.md
> +  Por exemplo, manter um *bloom filter* de todos os elementos que você inseriu pode deixar que você retorne rapidamente "sem correspondência" para pesquisas. Estes precisam ser pequenos e rápidos par
s/dados./dados

2019-09-02 12:16 UTC, danielfireman approved these changes

2019-09-28 05:22 UTC, dgryski commented
Sorry, missed this had been approved for merge.

2019-09-28 05:22 UTC, merged